name: docker

on:
  push:
    branches: [master]

jobs:
  docker-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Build & Push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: cyberryteam/bleemeo-hackathon-2020
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest"
        dockerfile: Dockerfile
    - name: AWS EC2 Deployement
      uses: fifsky/ssh-action@master
      with:
        command: |
          docker stop bleemeo
          docker rm bleemeo
          docker pull cyberryteam/bleemeo-hackathon-2020:latest
          docker run -d -p 80:80 --name=bleemeo cyberryteam/bleemeo-hackathon-2020:latest
          docker image prune
        host: ${{ secrets.HOST }}
        user: ubuntu
        key: ${{ secrets.PRIVATE_KEY }}
