name: docker

on:
  push:
    branches: [master]

jobs:
  docker-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Build & Push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: cyberryteam/bleemeo-hackathon-2020
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest"
        dockerfile: Dockerfile
        
  docker-deploy:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Re-deploy
      run: echo "OK\n"
